import { IUserFolder } from "../interfaces/folder.interface";

export const MockFolders: IUserFolder[] = [
  {
    id: "1",
    profileId: "1",
    title: "Spain 2024 | MALAGA AND RONDA",
    description: "Folder 1 Description",
    sortOrder: 1,
    centerBottomColor: "#ADfffA",
    centerTopColor: "#AFDEF8",
    leftBottomColor: "#AFDEF8",
    leftTopColor: "#2FDEF1",
    rightBottomColor: "#AAF0F1",
    rightTopColor: "#AAF0F1",
    favoriteFotoId: "",
    url: "https://picsum.photos/id/28/400/300",
    privateAccess: 0,
  },
  {
    id: "2",
    profileId: "1",
    title: "PORTUGAL 2024 | PORTO",
    centerBottomColor: "#ADfffA",
    centerTopColor: "#AFDEF8",
    leftBottomColor: "#AFDEF8",
    leftTopColor: "#2FDEF1",
    rightBottomColor: "#AAF0F1",
    rightTopColor: "#AAF0F1",
    favoriteFotoId: "",
    description: "Folder 2 Description",
    sortOrder: 2,
    url: "https://picsum.photos/id/17/400/300",
    privateAccess: 0,
  },
  {
    id: "3",
    profileId: "1",
    title: "FRANCE 2024 | PARIS",
    centerBottomColor: "#ADfffA",
    centerTopColor: "#AFDEF8",
    leftBottomColor: "#AFDEF8",
    leftTopColor: "#2FDEF1",
    rightBottomColor: "#AAF0F1",
    rightTopColor: "#AAF0F1",
    favoriteFotoId: "",
    description: "Folder 3 Description",
    sortOrder: 3,
    url: "https://picsum.photos/id/10/400/300",
    privateAccess: 0,
  },
  {
    id: "4",
    profileId: "1",
    title: "GERMANY 2024 | FRANKFURT",
    centerBottomColor: "#ADfffA",
    centerTopColor: "#AFDEF8",
    leftBottomColor: "#AFDEF8",
    leftTopColor: "#2FDEF1",
    rightBottomColor: "#AAF0F1",
    rightTopColor: "#AAF0F1",
    favoriteFotoId: "",
    description: "Folder 4 Description",
    sortOrder: 4,
    url: "https://picsum.photos/id/22/400/300",
  },
  {
    id: "5",
    profileId: "1",
    title: "USA 2024 | HOUSTON",
    centerBottomColor: "#ADfffA",
    centerTopColor: "#AFDEF8",
    leftBottomColor: "#AFDEF8",
    leftTopColor: "#2FDEF1",
    rightBottomColor: "#AAF0F1",
    rightTopColor: "#AAF0F1",
    favoriteFotoId: "",
    description: "Folder 5 Description",
    sortOrder: 5,
    url: "https://picsum.photos/id/21/400/300",
    privateAccess: 0,
  },
  {
    id: "6",
    profileId: "1",
    title: "ITALY 2024 | ROMA",
    centerBottomColor: "#ADfffA",
    centerTopColor: "#AFDEF8",
    leftBottomColor: "#AFDEF8",
    leftTopColor: "#2FDEF1",
    rightBottomColor: "#AAF0F1",
    rightTopColor: "#AAF0F1",
    favoriteFotoId: "",
    description: "Folder 6 Description",
    sortOrder: 6,
    url: "https://picsum.photos/id/15/400/300",
    privateAccess: 0,
  },
  {
    id: "7",
    profileId: "1",
    title: "JAPAN 2024 | TOKYO",
    centerBottomColor: "#ADfffA",
    centerTopColor: "#AFDEF8",
    leftBottomColor: "#AFDEF8",
    leftTopColor: "#2FDEF1",
    rightBottomColor: "#AAF0F1",
    rightTopColor: "#AAF0F1",
    favoriteFotoId: "",
    description: "Folder 7 Description",
    sortOrder: 7,
    url: "https://picsum.photos/id/12/400/300",
    privateAccess: 0,
  },
  {
    id: "8",
    profileId: "1",
    title: "CHINA 2024 | BEIJING",
    centerBottomColor: "#ADfffA",
    centerTopColor: "#AFDEF8",
    leftBottomColor: "#AFDEF8",
    leftTopColor: "#2FDEF1",
    rightBottomColor: "#AAF0F1",
    rightTopColor: "#AAF0F1",
    favoriteFotoId: "",
    description: "Folder 8 Description",
    sortOrder: 8,
    url: "https://picsum.photos/id/23/400/300",
    privateAccess: 0,
  },
  {
    id: "9",
    profileId: "1",
    title: "New Zealand 2024 | AUCKLAND",
    centerBottomColor: "#ADfffA",
    centerTopColor: "#AFDEF8",
    leftBottomColor: "#AFDEF8",
    leftTopColor: "#2FDEF1",
    rightBottomColor: "#AAF0F1",
    rightTopColor: "#AAF0F1",
    favoriteFotoId: "",
    description: "Folder 9 Description",
    sortOrder: 9,
    url: "https://picsum.photos/id/11/400/300",
    privateAccess: 0,
  },
];
